config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
    member do
      put :change
    end
  end
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  resources :tasks
  devise_for :users

  root 'pages#home'

  get 'about' => "pages#about"
  get 'test' => "pages#test"

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user  

	validates :user_id, presence: true
	validates :content, presence: true

	auto_html_for :content do
		html_escape
		image
		youtube(:width => "1000", :height => 250, :autoplay => false)
		link :target => "_blank", :rel => "nofollow"
		simple_format
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy               
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  if current_user
  	  redirect_to tasks_path
  end
 end
  
  def about
  end

  def test 
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @to_do = current_user.tasks.where(state: "to_do")
    @doing = current_user.tasks.where(state: "doing")
    @done = current_user.tasks.where(state: "done")
      end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change
    @task.update_attributes(state: params[:state])
    respond_to do |format|
      format.html {redirect_to tasks_path}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:content,   :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "stukdo", root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li></li>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          
        </div>
        
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <li><%= link_to "settings", edit_user_registration_path %></li>
       <li><%= link_to "log out", destroy_user_session_path, method: :delete %></li> 
      <% else %>
      <li><%= link_to "About", about_path %></li>
        <li><%=  link_to "login", new_user_session_path
           %></li>
           <% end %>
        
           
        <li class="dropdown">
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukdo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header"%>	
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>Our vision is to improve people's productivity</p>

app/views/pages/home.html.erb
<h1>Hammad khan</h1>
<div class="jumbotron">
	<h1><i class="fa fa-circle-o-notch"></i>  Stukdo</h1>
<p>This is my smart to do app,made with Ruby on Rails</p>	
<%= link_to "sign up", new_user_registration_path , class: 'btn btn-primary-lg' %>
</div>

app/views/pages/test.html.erb
<div class="row">
	<div class="col-md-4"><h1 class="text-center">To Do</h1>

	<div class="panel panel-info">
	<div class="panel-heading">Heading</div>
	<div class="panel-body">content</div>
	<div class="panel-footer text-center">footer</div>
	</div>	


    </div>
	<div class="col-md-4"><h1 class="text-center">Doing</h1></div>
	<div class="col-md-4"><h1 class="text-center">Done</h1></div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

  
    <%= f.input :content, label: false, required: true, autofocus: true, input_html: {class: "form-control"}, placeholder: "content" %>

  
    <%= f.button :submit, class: "btn btn-lg btn-primary btn-block" %>
 
<% end %>

app/views/tasks/_task.html.erb
    <!--
    <tr>
        <td><%= task.content %></td>
        <td><%= task.state %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <% if task.state == "doing" %>
        <td><%= link_to "Mark as doing", change_task_path(task, state: "doing"), method: :put%></td>
        <% else %>
        <td><%= link_to "Mark as to do", change_task_path(task, state: "to_do"), method: :put%></td>
         <td><%= link_to "Mark as done", change_task_path(task, state: "done"), method: :put%></td> 
         <% end %>

   
    </tr>
    -->



    <div class="panel panel-info">
	 <div class="panel-heading">created <%= time_ago_in_words(task.created_at) %> ago</div>

	 <%= link_to "x", task_path(task), method: :delete, data: {confirm: "Are you sure?"}, class: "pull-right" %>

	<div class="panel-body"><%= raw(task.content_html)%></div>


	 <div class="panel-footer text-center">
	 	    <% if task.state == "doing" %>
	 	    <div class="btn-group btn-group-justified"> 
        <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "to_do"), method: :put, class: "btn btn-info btn-md btn-block" %>
         <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-info btn-md btn-block" %>
     </div>

         <%elsif task.state =="done" %>
         <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-info btn-md btn-block" %>
         <%else %>
         <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-info btn-md btn-block" %>
         <% end %>
	 </div>
	</div>	

app/views/tasks/edit.html.erb
<h1 class="text-center">Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">
<div class="col-md-4"><h1 class="text-center">To Do</h1>
<%= render @to_do %>
</div>
<div class="col-md-4"><h1 class="text-center">Doing</h1>
<%= render @doing %>
</div>
<div class="col-md-4"><h1 class="text-center">Done</h1>
<%= render @done %>
</div>
</div>


<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>state:</strong>
  <%= @task.state %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>